### ISSUE TITLE
Would it be possible to have a signed release in the future?

### ISSUE THREAD

**Issue by Footmunch** [drewburlingame/ObjectPrinter#10]
Im currently using the object printer nugget in vs 2015 for logging, and its working really nice.
Only issue im having is, the DLL that is using it is signed, so that is causing issues.

I can manually sign it with this other tool i found on github, without having the source.
Its a temp workaround, so if the future releases are signed, it would be greatly appreciated.

**Comment by drewburlingame** [comment]
Hi.  This isn't work I'm particularly interested in taking on, but I'd be willing to accept a pull request.
