### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by drewburlingame** [drewburlingame/ObjectPrinter#9]

**Comment by chrisbobo** [comment]
@drewburlingame Documentation would be great, the existing docs and tests didn't help me figure out how to use it. I didn't spend a long time trying to use it. I had just assumed it would be super simple.

**Comment by drewburlingame** [comment]
default use case should be simple since it would use all default config settings and you don't have to do anything except call one of the dump extension methods.  how were you trying to use it that didn't work?  did you assume you had to supply a configuration?

**Comment by chrisbobo** [comment]
Well, turns out it is super simple.
